include $(GNUSTEP_MAKEFILES)/common.make
OBJCFLAGS = -fobjc-arc
LDFLAGS = -ldispatch
APP_NAME = FractionArcDemo
FractionArcDemo_OBJC_FILES = Fraction.m helloGCD_ARC_objc.m
include $(GNUSTEP_MAKEFILES)/application.make
